# desired features

features = {'livingSpace': 0,
 'newlyConst': 0,
 'buildingAge': 0,
 'balcony': 0,
 'hasKitchen': 0,
 'cellar': 0,
 'lift': 0,
 'garden': 0,
 'schufa_yn': 0,
 'PersonalInfo_yn': 0,
 'incomeProof_yn': 0,
 'guarantee_yn': 0,
 'debtFreeProof_yn': 0,
 'ID_yn': 0,
 'typeOfFlat_ground_floor': 0,
 'typeOfFlat_half_basement': 0,
 'typeOfFlat_loft': 0,
 'typeOfFlat_maisonette': 0,
 'typeOfFlat_penthouse': 0,
 'typeOfFlat_raised_ground_floor': 0,
 'typeOfFlat_roof_storey': 0,
 'typeOfFlat_terraced_flat': 0,
 'regio3_Buchholz': 0,
 'regio3_Charlottenburg': 0,
 'regio3_Friedrichshain': 0,
 'regio3_Hellersdorf': 0,
 'regio3_Hohenschönhausen': 0,
 'regio3_Kreuzberg': 0,
 'regio3_Köpenick': 0,
 'regio3_Lichtenberg': 0,
 'regio3_Marzahn': 0,
 'regio3_Neukölln': 0,
 'regio3_Pankow': 0,
 'regio3_Prenzlauer Berg': 0,
 'regio3_Reinickendorf': 0,
 'regio3_Schöneberg': 0,
 'regio3_Spandau': 0,
 'regio3_Steglitz': 0,
 'regio3_Tempelhof': 0,
 'regio3_Tiergarten': 0,
 'regio3_Treptow': 0,
 'regio3_Wedding': 0,
 'regio3_Weißensee': 0,
 'regio3_Wilmersdorf': 0,
 'regio3_Zehlendorf': 0}
